# Generated by Django 3.0.8 on 2020-07-28 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('tel', models.CharField(max_length=12, null=True)),
                ('name', models.CharField(default='', max_length=30, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, null=True, verbose_name='Фамилия')),
                ('date_birth', models.DateField(max_length=10, null=True, verbose_name='Дата рожения: ДД.ММ.ГГГГ')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='Компания')),
                ('bank_card', models.CharField(max_length=20, null=True, verbose_name='Номер карты')),
                ('is_player', models.BooleanField(default=False, null=True)),
                ('is_developer', models.BooleanField(default=False, null=True)),
                ('is_administrator', models.BooleanField(default=False, null=True)),
                ('bank_cаrd', models.CharField(max_length=20, null=True, verbose_name='Номер карты')),
                ('foto', models.ImageField(null=True, upload_to='img/%Y/%m', verbose_name='Аватар')),
                ('strategy', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('rpg', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('f2p', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('shooter', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('racing', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('horror', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('stealth', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('survival_horror', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('sports', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('party', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('platform', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('puzzle', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('god_game', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('flight_simulation', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('fighting', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('beatemup', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('adventure', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
                ('action', models.CharField(max_length=20, null=True, verbose_name='Предпочтильный жанр')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок записи')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('description', models.TextField(max_length=160, verbose_name='Короткое описание')),
                ('data', models.DateField(verbose_name=datetime.date.today)),
                ('img', models.ImageField(null=True, upload_to='img/%Y/%m', verbose_name='Изображение записи')),
                ('num_views', models.PositiveIntegerField(default=0)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок изображения')),
                ('img', models.ImageField(upload_to='img/%Y/%m', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('url', models.CharField(max_length=250, null=True)),
                ('short_description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(null=True, upload_to='img/%Y/%m', verbose_name='Изображение игры')),
                ('gameplay_video_link', models.CharField(max_length=250, null=True)),
                ('release_status', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('screenshots', models.ImageField(null=True, upload_to='img/%Y/%m')),
                ('description', models.TextField(default='')),
                ('genre', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='games.Account')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='games.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Comment', verbose_name='Родитель')),
                ('user', models.ForeignKey(default='NoName', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
