# Generated by Django 3.0.8 on 2020-08-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
    ]
