# Generated by Django 3.0.8 on 2020-07-28 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_release',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='game',
            name='sale_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='games.Account'),
        ),
    ]
