# Generated by Django 3.0.8 on 2020-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Жанр')),
                ('strategy', models.IntegerField(default=0)),
                ('rpg', models.IntegerField(default=0)),
                ('f2p', models.IntegerField(default=0)),
                ('shooter', models.IntegerField(default=0)),
                ('racing', models.IntegerField(default=0)),
                ('horror', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('survival_horror', models.IntegerField(default=0)),
                ('sports', models.IntegerField(default=0)),
                ('party', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('puzzle', models.IntegerField(default=0)),
                ('god_game', models.IntegerField(default=0)),
                ('flight_simulation', models.IntegerField(default=0)),
                ('fighting', models.IntegerField(default=0)),
                ('beatemup', models.IntegerField(default=0)),
                ('adventure', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
                ('simylate', models.IntegerField(default=0)),
                ('mmo', models.IntegerField(default=0)),
            ],
        ),
    ]
