# Generated by Django 3.0.8 on 2020-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rait',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='action',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='adventure',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='beatemup',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='f2p',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fighting',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='flight_simulation',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='god_game',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='horror',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='party',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='puzzle',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='racing',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='rpg',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shooter',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sports',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stealth',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='strategy',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
        migrations.AlterField(
            model_name='account',
            name='survival_horror',
            field=models.CharField(max_length=20, null=True, verbose_name='Предпочтительный жанр'),
        ),
    ]
