# Generated by Django 3.0.8 on 2020-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='count_dislikes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='count_likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='forthegame',
        ),
        migrations.AddField(
            model_name='game',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='num_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='fav',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='posts',
            name='fav_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
