# Generated by Django 3.0.8 on 2020-08-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='screenshots',
            new_name='img',
        ),
    ]
