# Generated by Django 3.0.8 on 2020-07-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200728_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_author', to='games.Account'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_author', to='games.Account')),
                ('game_rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rating', to='games.GameRating')),
            ],
        ),
        migrations.AddField(
            model_name='gamerating',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.Game'),
        ),
    ]
