# Generated by Django 3.0.8 on 2020-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
