# Generated by Django 3.0.8 on 2020-07-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20200728_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='game_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GameRating',
        ),
    ]
