# Generated by Django 3.0.8 on 2020-08-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_number_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_game', to='games.Game'),
        ),
    ]
