# Generated by Django 3.0.8 on 2020-07-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200729_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='f2p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='rpg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='strategy',
            field=models.IntegerField(default=0),
        ),
    ]
